[versions]
kotlin = "2.1.21"

[libraries]
jackson-dataformat-toml = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml:2.15.0-rc1"
junit = "junit:junit:4.13.2"
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

[plugins]
gradlePluginPublish = "com.gradle.plugin-publish:2.0.0"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
mavenPublish = "com.vanniktech.maven.publish.base:0.34.0"
shadow = "com.gradleup.shadow:9.1.0"
spotless = "com.diffplug.spotless:7.0.4"
versionCatalogUpdate = "nl.littlerobots.version-catalog-update:1.0.0"
